#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branch=$(git symbolic-ref HEAD | sed -e "s,.*/\\(.*\\),\\1,")
if [ "$branch" = "main" ]; then
    echo "You can't commit directly to main branch."
    exit 1
fi